/**
 * `offhook init` — interactive setup wizard.
 *
 * Asks the questions, collects the keys, writes agent.yaml + knowledge/ +
 * .env. The goal: from empty folder to a talkable test agent in under two
 * minutes, with `offhook chat` as the immediate next step (no voice keys
 * needed for that).
 */

import { intro, outro, text, select, password, confirm, isCancel, cancel, note } from '@clack/prompts';
import { writeFileSync, existsSync, mkdirSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';

const KEY_LINKS: Record<string, string> = {
  OPENROUTER_API_KEY: 'https://openrouter.ai/keys',
  OPENAI_API_KEY: 'https://platform.openai.com/api-keys',
  DEEPGRAM_API_KEY: 'https://console.deepgram.com',
  CARTESIA_API_KEY: 'https://play.cartesia.ai/keys',
};

function bail(value: unknown): asserts value is string | boolean {
  if (isCancel(value)) {
    cancel('Setup cancelled — nothing was written.');
    process.exit(0);
  }
}

export async function initCommand(targetDir: string): Promise<void> {
  intro('offhook — set up your voice agent');

  if (existsSync(join(targetDir, 'agent.yaml'))) {
    const overwrite = await confirm({ message: 'agent.yaml already exists here. Overwrite?', initialValue: false });
    bail(overwrite);
    if (!overwrite) {
      cancel('Keeping your existing agent.yaml.');
      process.exit(0);
    }
  }

  const template = await select({
    message: 'What should this agent do?',
    options: [
      { value: 'receptionist', label: 'Business receptionist', hint: 'hours, FAQ, messages, transfer' },
      { value: 'secretary', label: 'Personal secretary', hint: 'screens calls, takes messages' },
      { value: 'blank', label: 'Start blank' },
    ],
  });
  bail(template);

  const businessName = await text({
    message: template === 'secretary' ? 'Whose calls does it answer? (your name)' : 'Business name',
    placeholder: template === 'secretary' ? 'Alex Rivera' : 'Bright Smile Dental',
    validate: v => (v && v.trim().length > 0 ? undefined : 'Required'),
  });
  bail(businessName);

  const agentName = await text({
    message: "Agent's name (what it calls itself)",
    placeholder: 'June',
    defaultValue: 'June',
  });
  bail(agentName);

  const llmChoice = await select({
    message: 'Which LLM should power it?',
    options: [
      { value: 'openrouter', label: 'OpenRouter (recommended)', hint: 'one key, every hosted model — GPT, Qwen, DeepSeek, Llama...' },
      { value: 'openai', label: 'OpenAI directly' },
      { value: 'ollama', label: 'Local via Ollama', hint: 'no key, runs on your machine' },
    ],
  });
  bail(llmChoice);

  let model = 'gpt-5.4-mini';
  let llmYaml = '  llm: gpt-5.4-mini';
  const envLines: string[] = [];

  if (llmChoice === 'openrouter') {
    const m = await text({
      message: 'Model (OpenRouter id)',
      placeholder: 'openai/gpt-5.4-mini',
      defaultValue: 'openai/gpt-5.4-mini',
    });
    bail(m);
    model = m as string;
    llmYaml = `  llm:\n    provider: openrouter\n    model: ${model}`;
    const key = await password({ message: `OPENROUTER_API_KEY (get one: ${KEY_LINKS.OPENROUTER_API_KEY})` });
    bail(key);
    envLines.push(`OPENROUTER_API_KEY=${key}`);
  } else if (llmChoice === 'openai') {
    const key = await password({ message: `OPENAI_API_KEY (get one: ${KEY_LINKS.OPENAI_API_KEY})` });
    bail(key);
    envLines.push(`OPENAI_API_KEY=${key}`);
  } else {
    const m = await text({
      message: 'Ollama model (must be pulled locally)',
      placeholder: 'llama3.3',
      defaultValue: 'llama3.3',
    });
    bail(m);
    model = m as string;
    llmYaml = `  llm:\n    provider: ollama\n    model: ${model}`;
  }

  // No separate "voice keys" step: speech defaults to OpenAI, so a single
  // OpenAI key already powers STT + LLM + TTS. Deepgram/Cartesia are an
  // optional production upgrade, documented (commented) in the generated config.

  // ---- write files --------------------------------------------------
  const id = (businessName as string).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  const instructions = template === 'secretary'
    ? `\n  instructions: >\n    You answer when ${businessName} can't. Find out who's calling and what\n    it's about, take a message with a callback number, and keep it brief.\n`
    : '\n';

  const agentYaml = `# Generated by \`offhook init\` — edit freely. Docs: https://github.com/sekhar197/offhook
agent:
  id: ${id}
  businessName: ${JSON.stringify(businessName)}
  agentName: ${JSON.stringify(agentName)}
  tone: ${template === 'secretary' ? 'casual' : 'warm'}${instructions}
business:
  # address: 12 Main St
  # phone: "5551234567"
  # hours:
  #   monday: from 9 AM to 5 PM
  policies: {}

knowledge:
  folder: ./knowledge

tools:
  enabled: [answer_from_knowledge, take_message, transfer_to_human, end_call]
  # transferPhone: "+15550001111"
  # webhookUrl: https://your-server.example.com/offhook

# voice: speech defaults to OpenAI — one OPENAI_API_KEY powers STT + LLM + TTS.
#   Production-quality upgrade (optional):
#     stt: { provider: deepgram, model: nova-3 }                       # DEEPGRAM_API_KEY
#     tts: { provider: cartesia, model: sonic-3, voice: "<voice-id>" } # CARTESIA_API_KEY
#   Fully local (no API keys): { provider: openai-compatible, baseUrl: "http://localhost:8080/v1" }

models:
${llmYaml}
`;

  writeFileSync(join(targetDir, 'agent.yaml'), agentYaml);
  mkdirSync(join(targetDir, 'knowledge'), { recursive: true });
  const kbPath = join(targetDir, 'knowledge', 'getting-started.md');
  if (!existsSync(kbPath)) {
    writeFileSync(kbPath, `# General

## What ${businessName} does
Replace this with a real description — the agent answers caller questions from the files in this folder.

## How to reach a person
Edit tools.transferPhone in agent.yaml so the agent can transfer callers.
`);
  }
  if (envLines.length > 0) {
    appendFileSync(join(targetDir, '.env'), envLines.join('\n') + '\n');
  }
  // keep keys out of git even if the user inits a repo here later
  if (!existsSync(join(targetDir, '.gitignore'))) {
    writeFileSync(join(targetDir, '.gitignore'), '.env\n');
  }

  note(
    [
      'agent.yaml          your agent (edit freely)',
      'knowledge/          drop .md / .yaml files — the agent answers from them',
      envLines.length ? '.env                your keys (gitignored)' : null,
    ].filter(Boolean).join('\n'),
    'Created',
  );

  outro('Next: `offhook doctor` to verify, then `offhook chat` to talk to it.');
}
